name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing-config:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [ '3.8', '3.9', '3.10' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Run Python tests 
      run: |
        sudo mkdir /etc/pdns-exporter/
        sudo python3 -m pip install -r requirements.txt 
        sudo python3 -m unittest tests.test_config -v

  testing-api:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - pdns-version: "44"
            branch: "auth-4.4.x"
          - pdns-version: "45"
            branch: "auth-4.5.x" 

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Setup MariaDB
      run: |
        sudo docker run -d --network="host" --name mariadb -e MARIADB_ROOT_PASSWORD=secret -e MARIADB_DATABASE=powerdns -e MARIADB_USER=powerdns -e MARIADB_PASSWORD=powerdns mariadb:latest
        sudo docker exec -i mariadb sh -c 'exec mysqladmin ping -h 127.0.0.1 -u root --password=secret --wait=30'

    - name: Import sql schema
      run: |
        sudo wget https://raw.githubusercontent.com/PowerDNS/pdns/rel/${{ matrix.branch }}/modules/gmysqlbackend/schema.mysql.sql
        sudo docker exec -i mariadb sh -c 'exec mysql -u root -p"secret" powerdns' < schema.mysql.sql

    - name: Setup PowerDNS
      run: |
        sudo docker run -d --network="host" --name powerdns --volume=$PWD/testdata/pdns.conf:/etc/powerdns/pdns.conf:ro powerdns/pdns-auth-${{ matrix.pdns-version }}:latest
        sudo chmod +x ./testdata/initzone.sh
        sudo ./testdata/initzone.sh

    - name: Run Python tests 
      run: |
        sudo python3 -m pip install -r requirements.txt 
        sudo python3 -m unittest tests.test_webapp -v
        sudo python3 -m unittest tests.test_package -v

    - name: Check zone format
      run: |
        sudo apt-get update && sudo apt-get install -y bind9utils
        sudo cat /tmp/db.zone.test
        sudo named-checkzone zone.test /tmp/db.zone.test
